stages:
  prepare:
    cmd: python src/prepare.py data/dataset/data.xml
    deps:
    - data/dataset/data.xml
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
  featurize:
    cmd: python src/featurization.py data/prepared data/features
    deps:
    - data/prepared
    - src/featurization.py
    params:
    - featurize.max_features
    - featurize.ngrams
    outs:
    - data/features
  train:
    cmd: python src/train.py data/features data/models/model.pkl
    deps:
    - data/features
    - src/train.py
    params:
    - train.min_split
    - train.n_est
    - train.seed
    outs:
    - data/models/model.pkl
  evaluate:
    cmd: python src/evaluate.py data/models/model.pkl data/features data/results/scores.json data/results/prc.json data/results/roc.json
    deps:
    - data/features
    - data/models/model.pkl
    - src/evaluate.py
    metrics:
    - data/results/scores.json:
        cache: false
    plots:
    - data/results/prc.json:
        cache: false
        x: recall
        y: precision
    - data/results/roc.json:
        cache: false
        x: fpr
        y: tpr
